#[derive(Debug, Hash, PartialEq, Eq, Clone, Copy)]
pub enum Button {
    RightClick,
    LeftClick,
    CentralClick,

    Other(u32), // when it is unknown
}


#[derive(Debug, Hash, PartialEq, Eq, Clone, Copy)]
pub enum Key {
    Key1,
    Key2,
    Key3,
    Key4,
    Key5,
    Key6,
    Key7,
    Key8,
    Key9,
    Key0,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Escape,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    Snapshot,
    Scroll,
    Pause,
    Insert,
    Home,
    Delete,
    End,
    PageDown,
    PageUp,
    Left,
    Up,
    Right,
    Down,
    Back,
    Return,
    Space,
    Compose,
    Caret,
    Numlock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    AbntC1,
    AbntC2,
    Add,
    Apostrophe,
    Apps,
    At,
    Ax,
    Backslash,
    Calculator,
    Capital,
    Colon,
    Comma,
    Convert,
    Decimal,
    Divide,
    Equals,
    Grave,
    Kana,
    Kanji,
    LAlt,
    LBracket,
    LControl,
    LShift,
    LWin,
    Mail,
    MediaSelect,
    MediaStop,
    Minus,
    Multiply,
    Mute,
    MyComputer,
    NavigateForward,
    NavigateBackward,
    NextTrack,
    NoConvert,
    NumpadComma,
    NumpadEnter,
    NumpadEquals,
    OEM102,
    Period,
    PlayPause,
    Power,
    PrevTrack,
    RAlt,
    RBracket,
    RControl,
    RShift,
    RWin,
    Semicolon,
    Slash,
    Sleep,
    Stop,
    Subtract,
    Sysrq,
    Tab,
    Underline,
    Unlabeled,
    VolumeDown,
    VolumeUp,
    Wake,
    WebBack,
    WebFavorites,
    WebForward,
    WebHome,
    WebRefresh,
    WebSearch,
    WebStop,
    Yen,
    Copy,
    Paste,
    Cut,

    Other(u32), // when it is unknown
}

impl Key {
    pub fn convert_key(key: Option<glium::glutin::event::VirtualKeyCode>, scancode: u32) -> Self {
        // https://docs.rs/glutin/0.21.2/glutin/enum.VirtualKeyCode.html
        use glium::glutin::event::VirtualKeyCode::*;
        match key {
            None => Self::Other(scancode),
            Some(known_key) => match known_key {
                Key1 => Self::Key1,
                Key2 => Self::Key2,
                Key3 => Self::Key3,
                Key4 => Self::Key4,
                Key5 => Self::Key5,
                Key6 => Self::Key6,
                Key7 => Self::Key7,
                Key8 => Self::Key8,
                Key9 => Self::Key9,
                Key0 => Self::Key0,
                A => Self::A,
                B => Self::B,
                C => Self::C,
                D => Self::D,
                E => Self::E,
                F => Self::F,
                G => Self::G,
                H => Self::H,
                I => Self::I,
                J => Self::J,
                K => Self::K,
                L => Self::L,
                M => Self::M,
                N => Self::N,
                O => Self::O,
                P => Self::P,
                Q => Self::Q,
                R => Self::R,
                S => Self::S,
                T => Self::T,
                U => Self::U,
                V => Self::V,
                W => Self::W,
                X => Self::X,
                Y => Self::Y,
                Z => Self::Z,
                Escape => Self::Escape,
                F1 => Self::F1,
                F2 => Self::F2,
                F3 => Self::F3,
                F4 => Self::F4,
                F5 => Self::F5,
                F6 => Self::F6,
                F7 => Self::F7,
                F8 => Self::F8,
                F9 => Self::F9,
                F10 => Self::F10,
                F11 => Self::F11,
                F12 => Self::F12,
                F13 => Self::F13,
                F14 => Self::F14,
                F15 => Self::F15,
                F16 => Self::F16,
                F17 => Self::F17,
                F18 => Self::F18,
                F19 => Self::F19,
                F20 => Self::F20,
                F21 => Self::F21,
                F22 => Self::F22,
                F23 => Self::F23,
                F24 => Self::F24,
                Snapshot => Self::Snapshot,
                Scroll => Self::Scroll,
                Pause => Self::Pause,
                Insert => Self::Insert,
                Home => Self::Home,
                Delete => Self::Delete,
                End => Self::End,
                PageDown => Self::PageDown,
                PageUp => Self::PageUp,
                Left => Self::Left,
                Up => Self::Up,
                Right => Self::Right,
                Down => Self::Down,
                Back => Self::Back,
                Return => Self::Return,
                Space => Self::Space,
                Compose => Self::Compose,
                Caret => Self::Caret,
                Numlock => Self::Numlock,
                Numpad0 => Self::Numpad0,
                Numpad1 => Self::Numpad1,
                Numpad2 => Self::Numpad2,
                Numpad3 => Self::Numpad3,
                Numpad4 => Self::Numpad4,
                Numpad5 => Self::Numpad5,
                Numpad6 => Self::Numpad6,
                Numpad7 => Self::Numpad7,
                Numpad8 => Self::Numpad8,
                Numpad9 => Self::Numpad9,
                AbntC1 => Self::AbntC1,
                AbntC2 => Self::AbntC2,
                Add => Self::Add,
                Apostrophe => Self::Apostrophe,
                Apps => Self::Apps,
                At => Self::At,
                Ax => Self::Ax,
                Backslash => Self::Backslash,
                Calculator => Self::Calculator,
                Capital => Self::Capital,
                Colon => Self::Colon,
                Comma => Self::Comma,
                Convert => Self::Convert,
                Decimal => Self::Decimal,
                Divide => Self::Divide,
                Equals => Self::Equals,
                Grave => Self::Grave,
                Kana => Self::Kana,
                Kanji => Self::Kanji,
                LAlt => Self::LAlt,
                LBracket => Self::LBracket,
                LControl => Self::LControl,
                LShift => Self::LShift,
                LWin => Self::LWin,
                Mail => Self::Mail,
                MediaSelect => Self::MediaSelect,
                MediaStop => Self::MediaStop,
                Minus => Self::Minus,
                Multiply => Self::Multiply,
                Mute => Self::Mute,
                MyComputer => Self::MyComputer,
                NavigateForward => Self::NavigateForward,
                NavigateBackward => Self::NavigateBackward,
                NextTrack => Self::NextTrack,
                NoConvert => Self::NoConvert,
                NumpadComma => Self::NumpadComma,
                NumpadEnter => Self::NumpadEnter,
                NumpadEquals => Self::NumpadEquals,
                OEM102 => Self::OEM102,
                Period => Self::Period,
                PlayPause => Self::PlayPause,
                Power => Self::Power,
                PrevTrack => Self::PrevTrack,
                RAlt => Self::RAlt,
                RBracket => Self::RBracket,
                RControl => Self::RControl,
                RShift => Self::RShift,
                RWin => Self::RWin,
                Semicolon => Self::Semicolon,
                Slash => Self::Slash,
                Sleep => Self::Sleep,
                Stop => Self::Stop,
                Subtract => Self::Subtract,
                Sysrq => Self::Sysrq,
                Tab => Self::Tab,
                Underline => Self::Underline,
                Unlabeled => Self::Unlabeled,
                VolumeDown => Self::VolumeDown,
                VolumeUp => Self::VolumeUp,
                Wake => Self::Wake,
                WebBack => Self::WebBack,
                WebFavorites => Self::WebFavorites,
                WebForward => Self::WebForward,
                WebHome => Self::WebHome,
                WebRefresh => Self::WebRefresh,
                WebSearch => Self::WebSearch,
                WebStop => Self::WebStop,
                Yen => Self::Yen,
                Copy => Self::Copy,
                Paste => Self::Paste,
                Cut => Self::Cut,
            },
        }
    }
}
